artifact_location: /home/hong-mai/Desktop/HONGMAI/Coding/ai-customer-growth-retention/notebooks/churn-lightgbm/0
creation_time: 1768572520515
experiment_id: '0'
last_update_time: 1768572520515
lifecycle_stage: active
name: Default
